/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop2project;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.TextField;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static oop2project.Login.userID;

/**
 *
 * @author rana-
 */
public class View1 extends javax.swing.JFrame {

        JTextField[] texts;
        JButton[] delete;
        JButton[] update;
        int[] ids;
        
        static int appoID;

    public View1() {
    initComponents();
    jPanel2.setLayout(new GridLayout(0, 3, 10, 10));
    

    try {
    String url = "jdbc:mysql://localhost:3306/hospital?useSSL=false";
    Connection con = DriverManager.getConnection(url, "", "");

    Statement s = con.createStatement();
    String query = String.format("SELECT * FROM appointment WHERE user_id = '%d'", userID); //make sure id is added as global varible in login page

    ResultSet reSet = s.executeQuery(query);

    ArrayList<String> clinics = new ArrayList<>();
    ArrayList<String> dates = new ArrayList<>();
    ArrayList<Integer> ides = new ArrayList<>();
    while (reSet.next()) {
        clinics.add(reSet.getString("clinic")); 
        ides.add(Integer.parseInt(reSet.getString("appo_id"))); 
        dates.add(reSet.getString("date")); 
    }
    
    int x = clinics.size();
    texts = new JTextField[x];
    update = new JButton[x];
    delete = new JButton[x];
    ids = new int[x];
    
    for (int i = 0; i < x; i++) {
        int index = i;

        
        texts[i] = new JTextField(clinics.get(i)+" | "+dates.get(i)); 
        texts[i].setEditable(false);
        
        ids[i] = ides.get(i);
        

        update[i] = new JButton("Update");
        update[i].setBackground(new java.awt.Color(0, 153, 255));
        update[i].setForeground(Color.white);

        delete[i] = new JButton("Delete");
        delete[i].setBackground(new java.awt.Color(255, 102, 102));
        delete[i].setForeground(Color.white);

        
        jPanel2.add(texts[i]);
        jPanel2.add(update[i]);
        jPanel2.add(delete[i]);

        
        delete[i].addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    
                    String url = "jdbc:mysql://localhost:3306/hospital?useSSL=false";
                    Connection con = DriverManager.getConnection(url, "", "");

                    
                    String deleteQuery = String.format("DELETE FROM appointment WHERE appo_id = %d", ids[index]);
                    Statement deleteStmt = con.createStatement();
                    deleteStmt.executeUpdate(deleteQuery);
                    
                    
                    
                    jPanel2.remove(texts[index]);
                    jPanel2.remove(update[index]);
                    jPanel2.remove(delete[index]);

                    
                    jPanel2.revalidate();
                    jPanel2.repaint();
                    
                    
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        });

        
        update[i].addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                appoID = ids[index];
                
                UpdateApp2 frme = new UpdateApp2();
                frme.setVisible(true);
               
            }
        });
    }

    con.close();

    
    jPanel2.revalidate();
    jPanel2.repaint();

} catch (SQLException ex) {
    ex.printStackTrace();
}
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(450, 300));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel1.setText("Upcoming Appointment ");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 224, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 199, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu4.setBackground(new java.awt.Color(255, 204, 204));
        jMenu4.setText("File");
        jMenu4.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N

        jMenuItem5.setMnemonic('A');
        jMenuItem5.setText("About");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
                jMenuItem5about(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuItem6.setText("Exit");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6Exit(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuBar2.add(jMenu4);

        jMenu6.setText("Profile");
        jMenu6.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        jMenu6.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu6logOut(evt);
            }
        });
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });
        jMenuBar2.add(jMenu6);

        jMenu5.setText("Home");
        jMenu5.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        jMenu5.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu5logOut(evt);
            }
        });
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });
        jMenuBar2.add(jMenu5);

        jMenu10.setText("Appotments");
        jMenu10.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N

        jMenuItem7.setText("Bock New Appotments");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7Bock(evt);
            }
        });
        jMenu10.add(jMenuItem7);

        jMenuItem8.setText("View My Appointments");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8GoView(evt);
            }
        });
        jMenu10.add(jMenuItem8);

        jMenuBar2.add(jMenu10);

        jMenu11.setText("Log out");
        jMenu11.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        jMenu11.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu11logOut(evt);
            }
        });
        jMenuBar2.add(jMenu11);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem5about(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5about
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this.jMenuBar2,"hospital management system that allows the patient to book an appointment, view previous appointments, and updating or deleting appointment data.");
    }//GEN-LAST:event_jMenuItem5about

    private void jMenuItem6Exit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6Exit
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem6Exit

    private void jMenu6logOut(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu6logOut
        // TODO add your handling code here:
        Profile frm = new Profile();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu6logOut

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu6ActionPerformed

    private void jMenu5logOut(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu5logOut
        // TODO add your handling code here:
        Home frm = new Home();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu5logOut

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jMenuItem7Bock(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7Bock
        // TODO add your handling code here:
        NewApp2 frm = new NewApp2();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem7Bock

    private void jMenuItem8GoView(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8GoView
        // TODO add your handling code here:
        View1 frm = new View1();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem8GoView

    private void jMenu11logOut(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu11logOut
        // TODO add your handling code here:
        Login frm = new Login();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu11logOut

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
